### ISSUE TITLE
One or more namespaces failed to connect

### ISSUE THREAD

**Issue by tuanngodoan** [Art-em1s/csgoempire.py#2]
when init socket get error:

socketio.exceptions.ConnectionError: One or more namespaces failed to connect

init:
self.socket = self.sio.connect(url="wss://trade.csgoempire.com/",
                                           socketio_path='/s/',
                                           headers={"User-agent": user_agent},
                                           transports=['websocket'],
                                           namespaces='/trade')
                                           
 Python 3.9

**Comment by Art-em1s** [comment]
Try passing the .gg domain into the client.

I assume given you closed this, you figured it out. Bear in mind this lib is still under development and is as of yet unfinished.

**Comment by tuanngodoan** [comment]
@Art-em1s Thanks, i used wrong lib. Before i try python-client socket io. 
After change to 
python-engineio==3.14.2
python-socketio==4.3.1 
it's work

**Comment by tuanngodoan** [comment]
@Art-em1s But i can't authen socket. I dont know why, i tried authen socket with nodejs still working :/

**Comment by Art-em1s** [comment]
You need the specific versions defined in the requirements, any other version causes it not to work.
________________________________
